-- 연습 문제
--1. JOBS테이블 문제
--1) MIN_SALARY 컬럼이 10000이상인 JOB_TITLE 조회
SELECT JOB_TITLE FROM JOBS WHERE MIN_SALARY >= 10000;

--2) JOB_TITLE  컬럼이 PROGRAMMER 인 레코드 조회
SELECT * FROM JOBS WHERE  JOB_TITLE ='Programmer';
--대소문자 상관없이 한다면 문자열 관력 오라클 함수 : UPPER(), LOWER()
SELECT * FROM JOBS WHERE UPPER(JOB_TITLE) = 'PROGRAMMER';
SELECT * FROM JOBS WHERE LOWER(JOB_TITLE) = 'programmer';

--3) MAX_SALARY 컬럼의 최대값 조회
SELECT MAX(MAX_SALARY) FROM JOBS j ;

--min_salary 의 평균값보다 작은 행의 job_id, job_title 컬럼 조회 -> GROUP 진도 후에 다시 해보기
 SELECT JOB_ID , JOB_TITLE FROM JOBS j WHERE MIN_SALARY < AVG(MIN_SALARY); -- 아직은 오류

--2. LOCATIONS 테이블 문제
--1)CITY 컬럼이 LONDON인 POSTAL_CODE 컬럼조회
SELECT POSTAL_CODE FROM LOCATIONS WHERE CITY ='London';
SELECT POSTAL_CODE FROM LOCATIONS WHERE CITY ='Seattle';

--2) LOCATION_ID 컬럼이 1700,2700,2500 이 아니고 CITY 컬럼이 TOKYO인 행의 모든 커럼 조회
SELECT * FROM LOCATIONS WHERE LOCATION_ID NOT IN (1700,2700,2500) AND CITY ='Tokyo';