-- 쇼핑몰 예시 (고객이 상품을 구매한다.)
--고객테이블
CREATE TABLE TBL_CUSTOM(
	CUSTOM_ID VARCHAR2(20),	--영문/숫자/기호
	NAME NVARCHAR2(20),		--한글등 다국어 문자 갯수
	EMIL VARCHAR2(20),
	AGE NUMBER(3),
	REG_DATE TIMESTAMP DEFAULT SYSDATE
);
--상품 테이블 : 상품 코드(가변길이 20자리),카테고리(고정길이 2자리)
--									A1:전자제품, B1:식품
CREATE TABLE TBL_PRODUCT(
	PCODE VARCHAR2(20),
	CATEGORY CHAR(2),
	PNAME NVARCHAR2(20),
	PRICE NUMBER(9)
);

--구매 테이블 : 어느 고객이 무슨 상품을 구입하는가?
CREATE TABLE TBL_BUY(
	CUSTOM_ID VARCHAR2(20),
	PCODE VARCHAR2(20),
	QUANTITY NUMBER(5),		--수량
	BUY_DATE TIMESTAMP
);

--테이터의 추가 : INSERT
INSERT INTO TBL_CUSTOM
(CUSTOM_ID, NAME, EMIL, AGE, REG_DATE)
VALUES('mina012', '김미나', 'kimm@gmail.com', 20, SYSDATE);
INSERT INTO TBL_CUSTOM
(CUSTOM_ID, NAME, EMIL, AGE, REG_DATE)
VALUES('hongGD', '홍길동', 'gil@korea.com', 32, SYSDATE);
INSERT INTO TBL_CUSTOM
(CUSTOM_ID, NAME, EMIL, AGE, REG_DATE)
VALUES('yummi', '유미', 'yumm@daum.net', 28, SYSDATE);
INSERT INTO TBL_CUSTOM
(CUSTOM_ID, NAME, EMIL, AGE, REG_DATE)
VALUES('mj', '명준', 'MJ@naver.com', 29, SYSDATE);

--중요1: CUSTOM 테이블의 행(ROW)데이터를 구분한 CUSTOM_ID,PCODE 는 중복되면 안된다.
INSERT INTO TBL_CUSTOM
(CUSTOM_ID, NAME, EMIL, AGE, REG_DATE)
VALUES('mj', '최모모', 'CHOI@naver.com', 33, SYSDATE);


INSERT INTO TBL_PRODUCT
(PCODE, CATEGORY, PNAME, PRICE)
VALUES('IPAD011', 'A1', '아이패드10', 880000);
INSERT INTO TBL_PRODUCT
(PCODE, CATEGORY, PNAME, PRICE)
VALUES('DOWON123a', 'B1', '동원참치선물세트', 54000);
INSERT INTO TBL_PRODUCT
(PCODE, CATEGORY, PNAME, PRICE)
VALUES('dk_143', 'A2', '모션데스크', 234500);

--중요2: 예를들면 PRICE QUANTITY 등의 컬럼은 NULL이 되면 안된다.
--꼭 필수 데이터로 저장되어야 한다.
INSERT INTO TBL_PRODUCT
(PCODE, CATEGORY, PNAME)
VALUES('dk_143', 'A2', '자동모션데스크');


--김미나가 아이패드 1개를 어제 구매했습니다.
INSERT INTO TBL_BUY
(CUSTOM_ID, PCODE, QUANTITY, BUY_DATE)
VALUES('mina012', 'IPAD011', 1, '2022-02-06');
--홍길동이 아이패드 2개를 오늘 구매했습니다
INSERT INTO TBL_BUY
(CUSTOM_ID, PCODE, QUANTITY, BUY_DATE)
VALUES('hongGD', 'IPAD011', 2, '2022-02-07');
--명준이가 참치선물세트 3개를 어제 구매했습니다
INSERT INTO TBL_BUY
(CUSTOM_ID, PCODE, QUANTITY, BUY_DATE)
VALUES('mj', 'DOWON123a', 3, '2022-02-06');
--김미나가 모션데스크 1개를 오늘 구매했습니다
INSERT INTO TBL_BUY
(CUSTOM_ID, PCODE, QUANTITY, BUY_DATE)
VALUES('mina012', 'dk_143', 1, '2022-02-07');
--유미가 참치선물세트 2개를 오늘 구매했습니다.
INSERT INTO TBL_BUY
(CUSTOM_ID, PCODE, QUANTITY, BUY_DATE)
VALUES('yummi', 'DOWON123a', 2, '2022-02-07');

--중요3: 고객과 상품테이블에 없는 CUSTOM_ID ,PRICE 컬럼값을 사용하면 정확성이 떨어진다
INSERT INTO TBL_BUY
(CUSTOM_ID, PCODE, QUANTITY, BUY_DATE)
VALUES('mmi', 'D_123', 2, '2022-02-07');


SELECT * FROM TBL_BUY tb;
SELECT * FROM TBL_PRODUCT tp ;
SELECT * FROM TBL_CUSTOM tc ;






